"""initial schema

Revision ID: b79054f4422e
Revises:
Create Date: 2026-08-20 23:55:54.564355
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b79054f4422e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("git_commit", sa.String(length=64), nullable=True),
        sa.Column("random_seed", sa.Integer(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("artifact_path", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("git_commit", sa.String(length=64), nullable=True),
        sa.Column("random_seed", sa.Integer(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("fetched_count", sa.Integer(), nullable=False),
        sa.Column("inserted_count", sa.Integer(), nullable=False),
        sa.Column("duplicate_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("artifact_path", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projection_artifacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("fit_version", sa.String(length=64), nullable=False),
        sa.Column("source_model", sa.String(length=255), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("fit_article_count", sa.Integer(), nullable=False),
        sa.Column("fit_cutoff", sa.DateTime(timezone=True), nullable=True),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("stats", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fit_version", name="uq_projection_fit_version"),
    )
    with op.batch_alter_table("projection_artifacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_projection_artifacts_fit_version"), ["fit_version"], unique=False
        )

    op.create_table(
        "story_clusters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_title", sa.Text(), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=True),
        sa.Column("centroid_version", sa.Integer(), nullable=False),
        sa.Column("centroid_blob", sa.LargeBinary(), nullable=True),
        sa.Column("centroid_dimension", sa.Integer(), nullable=True),
        sa.Column("embedding_method", sa.String(length=32), nullable=False),
        sa.Column("article_count", sa.Integer(), nullable=False),
        sa.Column("distinct_domain_count", sa.Integer(), nullable=False),
        sa.Column("first_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("story_clusters", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_story_clusters_last_published_at"), ["last_published_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_story_clusters_topic"), ["topic"], unique=False)

    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("source_domain", sa.String(length=255), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_payload_hash", sa.String(length=64), nullable=False),
        sa.Column("normalized_text_hash", sa.String(length=64), nullable=False),
        sa.Column("normalized_title_hash", sa.String(length=64), nullable=False),
        sa.Column("extraction_method", sa.String(length=64), nullable=False),
        sa.Column("source_adapter", sa.String(length=64), nullable=False),
        sa.Column("is_near_duplicate", sa.Boolean(), nullable=False),
        sa.Column("duplicate_of_article_id", sa.Integer(), nullable=True),
        sa.Column("duplicate_reason", sa.String(length=64), nullable=True),
        sa.Column("duplicate_similarity", sa.Float(), nullable=True),
        sa.Column("ingestion_run_id", sa.Integer(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["duplicate_of_article_id"], ["articles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["ingestion_run_id"], ["ingestion_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_url", name="uq_articles_canonical_url"),
    )
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_articles_canonical_url"), ["canonical_url"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_articles_duplicate_of_article_id"),
            ["duplicate_of_article_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_articles_normalized_text_hash"), ["normalized_text_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_articles_normalized_title_hash"), ["normalized_title_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_articles_published_at"), ["published_at"], unique=False
        )
        batch_op.create_index(
            "ix_articles_published_domain", ["published_at", "source_domain"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_articles_source_domain"), ["source_domain"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_articles_topic"), ["topic"], unique=False)

    op.create_table(
        "claims",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("story_cluster_id", sa.Integer(), nullable=True),
        sa.Column("normalized_claim", sa.Text(), nullable=False),
        sa.Column("claim_hash", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("predicate", sa.Text(), nullable=True),
        sa.Column("object", sa.Text(), nullable=True),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extraction_method", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["story_cluster_id"], ["story_clusters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("story_cluster_id", "claim_hash", name="uq_claim_story_hash"),
    )
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_claims_claim_hash"), ["claim_hash"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_claims_story_cluster_id"), ["story_cluster_id"], unique=False
        )

    op.create_table(
        "claim_evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("excerpt_start", sa.Integer(), nullable=False),
        sa.Column("excerpt_end", sa.Integer(), nullable=False),
        sa.Column("stance", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("claim_evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_claim_evidence_article_id"), ["article_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_claim_evidence_claim_id"), ["claim_id"], unique=False)

    op.create_table(
        "cluster_memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("story_cluster_id", sa.Integer(), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column("assignment_method", sa.String(length=64), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["story_cluster_id"], ["story_clusters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_id", "story_cluster_id", name="uq_membership_article_story"),
    )
    with op.batch_alter_table("cluster_memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cluster_memberships_article_id"), ["article_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cluster_memberships_story_cluster_id"),
            ["story_cluster_id"],
            unique=False,
        )

    op.create_table(
        "embedding_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("fit_version", sa.String(length=64), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("vector_blob", sa.LargeBinary(), nullable=True),
        sa.Column("vector_path", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "article_id",
            "model_name",
            "method",
            "dimension",
            "fit_version",
            name="uq_embedding_identity",
        ),
    )
    with op.batch_alter_table("embedding_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_embedding_records_article_id"), ["article_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_embedding_records_cache_key"), ["cache_key"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("embedding_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_embedding_records_cache_key"))
        batch_op.drop_index(batch_op.f("ix_embedding_records_article_id"))

    op.drop_table("embedding_records")
    with op.batch_alter_table("cluster_memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cluster_memberships_story_cluster_id"))
        batch_op.drop_index(batch_op.f("ix_cluster_memberships_article_id"))

    op.drop_table("cluster_memberships")
    with op.batch_alter_table("claim_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claim_evidence_claim_id"))
        batch_op.drop_index(batch_op.f("ix_claim_evidence_article_id"))

    op.drop_table("claim_evidence")
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claims_story_cluster_id"))
        batch_op.drop_index(batch_op.f("ix_claims_claim_hash"))

    op.drop_table("claims")
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_articles_topic"))
        batch_op.drop_index(batch_op.f("ix_articles_source_domain"))
        batch_op.drop_index("ix_articles_published_domain")
        batch_op.drop_index(batch_op.f("ix_articles_published_at"))
        batch_op.drop_index(batch_op.f("ix_articles_normalized_title_hash"))
        batch_op.drop_index(batch_op.f("ix_articles_normalized_text_hash"))
        batch_op.drop_index(batch_op.f("ix_articles_duplicate_of_article_id"))
        batch_op.drop_index(batch_op.f("ix_articles_canonical_url"))

    op.drop_table("articles")
    with op.batch_alter_table("story_clusters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_story_clusters_topic"))
        batch_op.drop_index(batch_op.f("ix_story_clusters_last_published_at"))

    op.drop_table("story_clusters")
    with op.batch_alter_table("projection_artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projection_artifacts_fit_version"))

    op.drop_table("projection_artifacts")
    op.drop_table("ingestion_runs")
    op.drop_table("evaluation_runs")
    # ### end Alembic commands ###
